### ISSUE TITLE
Bot crashes when responding to user input

### ISSUE THREAD

**Issue by Sam-Gunawan** [Pejuanh-Hackathon/GenLingo#3]
https://github.com/Axeldarren/GenLingo/blob/682b7e729eb39ae952e50a616216b02f469c47a7/pages/GenLingo.py#L353C1-L358C73

Received error:
`httpx_sse._exceptions.SSEError: Expected response Content-Type to be 'text/event-stream', got 'application/json'`

**Comment by Axeldarren** [comment]
Resolved, proceeding to production right now
